services:
  backend:
    image: ghcr.io/synkov2102/invite-backend:master
    restart: unless-stopped
    env_file:
      - .env.backend.production
    environment:
      NODE_ENV: production
      PORT: 3001
    ports:
      - "127.0.0.1:8091:3001"

  frontend:
    image: ghcr.io/synkov2102/invite-frontend:master
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - .env.frontend.production
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      BACKEND_API_URL: http://backend:3001
    ports:
      - "127.0.0.1:8090:3000"
