import type { InviteSitePalette } from "@/lib/invite-site-types";

export type InvitePalette = InviteSitePalette;
export type InvitePalettePreset = InvitePalette & {
  id: string;
  label: string;
  mood: string;
};

export const invitePalettePresets: InvitePalettePreset[] = [
  {
    id: "alpine",
    label: "Альпийский",
    mood: "Холодный воздух и теплое золото",
    background: "#dce8e4",
    surface: "#f8fbf7",
    ink: "#18363a",
    photoText: "#ffffff",
    muted: "#61777a",
    accent: "#c38b36",
    line: "#9dbfba",
    veil: "rgba(248, 251, 247, 0.84)",
  },
  {
    id: "pine",
    label: "Хвоя",
    mood: "Глубокий хвойный лес и мягкое золото",
    background: "#d8e2da",
    surface: "#f4f8f1",
    ink: "#1c3327",
    photoText: "#ffffff",
    muted: "#5d7064",
    accent: "#b98a3c",
    line: "#acc5b6",
    veil: "rgba(244, 248, 241, 0.85)",
  },
  {
    id: "granite",
    label: "Гранит",
    mood: "Тёплый горный камень и бронза",
    background: "#e2ded6",
    surface: "#faf8f2",
    ink: "#2c2823",
    photoText: "#ffffff",
    muted: "#786f64",
    accent: "#9c7544",
    line: "#cbc3b5",
    veil: "rgba(250, 248, 242, 0.86)",
  },
  {
    id: "frost",
    label: "Ледник",
    mood: "Ледяная синева и прохладное серебро",
    background: "#dde9ef",
    surface: "#f6fbfe",
    ink: "#20384a",
    photoText: "#ffffff",
    muted: "#647a88",
    accent: "#5a8fa8",
    line: "#aecdda",
    veil: "rgba(246, 251, 254, 0.85)",
  },
  {
    id: "dawn",
    label: "Рассвет",
    mood: "Альпийский рассвет и мягкая роза",
    background: "#ece1de",
    surface: "#fdf8f4",
    ink: "#3a2b29",
    photoText: "#ffffff",
    muted: "#8a746e",
    accent: "#c47e6a",
    line: "#dcc4bb",
    veil: "rgba(253, 248, 244, 0.86)",
  },
  {
    id: "pearl",
    label: "Жемчуг",
    mood: "Тихая классика и теплый свет",
    background: "#eee7dc",
    surface: "#fffaf2",
    ink: "#292725",
    photoText: "#fff8ee",
    muted: "#7a7168",
    accent: "#9b734d",
    line: "#d9c8b3",
    veil: "rgba(255, 250, 242, 0.88)",
  },
  {
    id: "silk",
    label: "Silk",
    mood: "Milky silk, graphite type and warm nude accents",
    background: "#d5c7bd",
    surface: "#fffefd",
    ink: "#171514",
    photoText: "#ffffff",
    muted: "#6f6963",
    accent: "#b9a78f",
    line: "#ddd4cc",
    veil: "rgba(255, 254, 253, 0.88)",
  },
  {
    id: "sage",
    label: "Ботаника",
    mood: "Садовая зелень и белые цветы",
    background: "#dbe5d4",
    surface: "#f7fbf0",
    ink: "#203326",
    photoText: "#ffffff",
    muted: "#667460",
    accent: "#3f7b57",
    line: "#b6cfb5",
    veil: "rgba(247, 251, 240, 0.86)",
  },
  {
    id: "mist",
    label: "Ривьера",
    mood: "Морской синий и коралловый акцент",
    background: "#dceaf0",
    surface: "#f7fcff",
    ink: "#18344e",
    photoText: "#ffffff",
    muted: "#60778a",
    accent: "#e36b5b",
    line: "#a8cbd5",
    veil: "rgba(247, 252, 255, 0.86)",
  },
  {
    id: "graphite",
    label: "Графика",
    mood: "Черно-белая типографика и красный штрих",
    background: "#d9d9d6",
    surface: "#faf9f5",
    ink: "#151515",
    photoText: "#ffffff",
    muted: "#6a6a66",
    accent: "#d6372d",
    line: "#b8b8b2",
    veil: "rgba(250, 249, 245, 0.9)",
  },
  {
    id: "champagne",
    label: "Сицилия",
    mood: "Терракота, вино и вечернее солнце",
    background: "#ead8c9",
    surface: "#fff7ec",
    ink: "#3a231d",
    photoText: "#fff8ee",
    muted: "#86645a",
    accent: "#c64c32",
    line: "#d6b08e",
    veil: "rgba(255, 247, 236, 0.86)",
  },
  {
    id: "aqua",
    label: "Лагуна",
    mood: "Спокойная бирюза и мягкая морская пена",
    background: "#0e2c34",
    surface: "#eef6f5",
    ink: "#103039",
    photoText: "#eaf3f2",
    muted: "#5f7e83",
    accent: "#4f969c",
    line: "#c2dcdc",
    veil: "rgba(238, 246, 245, 0.84)",
  },
  {
    id: "sea-mist",
    label: "Морская дымка",
    mood: "Пыльный сине-серый и прохладный туман",
    background: "#1c333a",
    surface: "#f1f5f5",
    ink: "#243b42",
    photoText: "#f1f7f7",
    muted: "#6e8389",
    accent: "#6f9aa3",
    line: "#cedcdd",
    veil: "rgba(241, 245, 245, 0.85)",
  },
  {
    id: "mint-shore",
    label: "Мятный берег",
    mood: "Приглушённая морская зелень и белый песок",
    background: "#16332e",
    surface: "#eef6f1",
    ink: "#1f3a35",
    photoText: "#eef7f3",
    muted: "#5f7d76",
    accent: "#6aac9d",
    line: "#c8ddd5",
    veil: "rgba(238, 246, 241, 0.85)",
  },
  {
    id: "glacier",
    label: "Ледник",
    mood: "Ледяная синева и чистый горный воздух",
    background: "#0b2330",
    surface: "#eef6f9",
    ink: "#123244",
    photoText: "#eef6fb",
    muted: "#5e7a87",
    accent: "#5aa7c4",
    line: "#c4dce6",
    veil: "rgba(238, 246, 249, 0.84)",
  },
  {
    id: "deep-ocean",
    label: "Глубина",
    mood: "Глубокая бирюза и тёмная вода",
    background: "#06222b",
    surface: "#e9f5f4",
    ink: "#08303a",
    photoText: "#e6f4f3",
    muted: "#557d82",
    accent: "#1f8f9c",
    line: "#bcdedd",
    veil: "rgba(233, 245, 244, 0.84)",
  },
  {
    id: "aquamarine",
    label: "Аквамарин",
    mood: "Яркий аквамарин и морская пена",
    background: "#0d2e30",
    surface: "#ecf8f5",
    ink: "#103a39",
    photoText: "#ebf8f4",
    muted: "#5b8480",
    accent: "#2bb6a6",
    line: "#c1e4dd",
    veil: "rgba(236, 248, 245, 0.84)",
  },
  {
    id: "fjord",
    label: "Фьорд",
    mood: "Прохладный сине-зелёный и северный фьорд",
    background: "#16303a",
    surface: "#eef5f6",
    ink: "#1d3a44",
    photoText: "#eef6f7",
    muted: "#647f86",
    accent: "#4f8a93",
    line: "#c6dce0",
    veil: "rgba(238, 245, 246, 0.85)",
  },
  {
    id: "vanilla",
    label: "Поп-арт",
    mood: "Розовый праздник и яркий апельсин",
    background: "#f7d9e7",
    surface: "#f7f8f5",
    ink: "#392d43",
    photoText: "#ffffff",
    muted: "#806d82",
    accent: "#f47a23",
    line: "#ef8bbb",
    veil: "rgba(249, 228, 238, 0.9)",
  },
  {
    id: "clay",
    label: "Бургунди",
    mood: "Вино, пудровый розовый и свечи",
    background: "#e8d8dc",
    surface: "#fff6f5",
    ink: "#341923",
    photoText: "#fff2f4",
    muted: "#85636c",
    accent: "#8f243e",
    line: "#d5aeb8",
    veil: "rgba(255, 246, 245, 0.88)",
  },
  {
    id: "lavender",
    label: "Ирис",
    mood: "Фиолетовый, мята и вечерний сад",
    background: "#ded8e9",
    surface: "#fcf8ff",
    ink: "#35243f",
    photoText: "#faf1ff",
    muted: "#796988",
    accent: "#6f4bb8",
    line: "#b8d8cc",
    veil: "rgba(252, 248, 255, 0.88)",
  },
  {
    id: "blue",
    label: "Полночь",
    mood: "Темный зал, латунь и звездное небо",
    background: "#111827",
    surface: "#f4f0e8",
    ink: "#142033",
    photoText: "#ffffff",
    muted: "#69778c",
    accent: "#e2b75d",
    line: "#aeb9ca",
    veil: "rgba(244, 240, 232, 0.9)",
  },
  {
    id: "nocturne",
    label: "Театр",
    mood: "Черный бархат, слоновая кость и кармин",
    background: "#24201f",
    surface: "#f1e9dc",
    ink: "#201b19",
    photoText: "#ffffff",
    muted: "#74645e",
    accent: "#9f2735",
    line: "#bca798",
    veil: "rgba(241, 233, 220, 0.9)",
  },
];

export const invitePaletteCatalog = Object.fromEntries(
  invitePalettePresets.map((palette) => [palette.id, palette]),
) as Record<string, InvitePalettePreset>;

/** @deprecated Используйте invitePalettePresets или getPalettePreset. */
export const palettePresets = invitePalettePresets;

export function getPalettePreset(paletteId: string): InvitePalettePreset | undefined {
  return invitePaletteCatalog[paletteId];
}

export function getPalettePresets(paletteIds: readonly string[]): InvitePalettePreset[] {
  return paletteIds
    .map((paletteId) => getPalettePreset(paletteId))
    .filter((palette): palette is InvitePalettePreset => palette !== undefined);
}
